# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-14 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livefeeds', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livefeeds',
            options={'ordering': ['-timestamp', '-updated']},
        ),
        migrations.AddField(
            model_name='livefeeds',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
