# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-14 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livefeeds', '0003_livefeeds_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='livefeeds',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livefeeds',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
