# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-28 12:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nearby_places', '0002_new'),
    ]

    operations = [
        migrations.DeleteModel(
            name='new',
        ),
    ]
